default: true

# unordered list indent
MD007:
  indent: 2

# line-length
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true
