default: true

# unordered list formatting
MD004:
  style: dash

# unordered list indent
MD007:
  indent: 4

# line-length
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true

# allow non-unique headings for non-sibling nodes
MD024:
  allow_different_nesting: true
  siblings_only: true

# emphasis style
MD049:
  style: asterisk

# strong style
MD050:
  style: asterisk
